name: Rust

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run install
      run: cargo install --verbose --path .

    - name: Run bf-script
      run: |
        >>>++
      shell: rustplayground {0}

    - name: Upload release binary
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: https://uploads.github.com/repos/fwilhe2/rustplayground/releases/1/assets/rustplayground
        asset_path: ./target/debug/rustplayground
        asset_name: rustplayground
        asset_content_type: application/octet-stream